export const today = () => new Date().toLocaleDateString('en-CA', { timeZone: 'Asia/Kolkata' });
export const money = n => new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: 0 }).format(Number(n) || 0);
export const cities = ['Delhi', 'Gurgaon', 'Noida', 'Mumbai', 'Bangalore', 'Hyderabad', 'Pune', 'Jaipur'];
export function seed() {
  const date = today();
  return {
    version: 2, session: null,
    users: [
      { id: 'c1', role: 'company', name: 'Aravalli Infrastructure', email: 'company@obrix.demo', city: 'Gurgaon', phone: '9810012345', bio: 'Building thoughtful commercial and residential spaces across NCR.', skills: [], availability: 'Available' },
      { id: 'c2', role: 'company', name: 'Deccan Buildworks', email: 'deccan@obrix.demo', city: 'Pune', phone: '9820012345', bio: 'Industrial and urban infrastructure specialists.', skills: [], availability: 'Available' },
      { id: 't1', role: 'contractor', name: 'Vikram Construction Co.', email: 'contractor@obrix.demo', city: 'Delhi', phone: '9830012345', bio: 'Civil works, structural execution and reliable site teams. 12 years of experience.', skills: ['Civil works', 'RCC', 'Residential'], availability: 'Available', rating: 4.8 },
      { id: 't2', role: 'contractor', name: 'Patil Civil Associates', email: 'patil@obrix.demo', city: 'Pune', phone: '9840012345', bio: 'Precision construction for commercial developments.', skills: ['Commercial', 'Finishing'], availability: 'Available', rating: 4.7 },
      { id: 'w1', role: 'worker', name: 'Ramesh Kumar', email: 'worker@obrix.demo', city: 'Delhi', phone: '9850012345', bio: 'Experienced mason with a focus on quality brickwork.', skills: ['Masonry', 'Brickwork'], availability: 'Available', rate: 900, rating: 4.9 },
      { id: 'w2', role: 'worker', name: 'Suresh Yadav', email: 'suresh@obrix.demo', city: 'Noida', phone: '9860012345', bio: 'Certified electrician, residential and commercial sites.', skills: ['Electrical', 'Wiring'], availability: 'Available', rate: 1100, rating: 4.8 },
      { id: 'w3', role: 'worker', name: 'Priya Sharma', email: 'priya@obrix.demo', city: 'Gurgaon', phone: '9870012345', bio: 'Site supervision and safety coordination.', skills: ['Site supervision', 'Surveying'], availability: 'Available', rate: 1400, rating: 4.9 },
      { id: 'w4', role: 'worker', name: 'Imran Shaikh', email: 'imran@obrix.demo', city: 'Mumbai', phone: '9880012345', bio: 'Skilled formwork carpenter with eight years on site.', skills: ['Carpentry', 'Formwork'], availability: 'Available', rate: 1000, rating: 4.7 }
    ],
    projects: [
      { id: 'p1', companyId: 'c1', title: 'Skyline Residences · Phase II', city: 'Gurgaon', category: 'Residential', budget: 8500000, duration: 180, area: '42,000 sq ft', status: 'Open', progress: 0, description: 'RCC structure, masonry and finishing for a premium 48-unit residential development. Seeking an experienced execution partner with a reliable workforce.', deadline: '2027-03-30', createdAt: date },
      { id: 'p2', companyId: 'c1', title: 'Sector 62 Business Park', city: 'Noida', category: 'Commercial', budget: 12400000, duration: 240, area: '68,000 sq ft', status: 'Open', progress: 0, description: 'Shell-and-core construction of a modern business park. Scope includes structural works, service shafts and external development.', deadline: '2027-04-15', createdAt: date },
      { id: 'p3', companyId: 'c2', title: 'Wagholi Logistics Hub', city: 'Pune', category: 'Industrial', budget: 6200000, duration: 120, area: '32,000 sq ft', status: 'Open', progress: 0, description: 'Warehouse foundations, industrial flooring and a loading dock for a regional logistics operator.', deadline: '2027-05-01', createdAt: date },
      { id: 'p4', companyId: 'c1', contractorId: 't1', title: 'Greenfield Community Centre', city: 'Delhi', category: 'Public infrastructure', budget: 3200000, duration: 90, area: '12,500 sq ft', status: 'Active', progress: 38, description: 'A neighbourhood community centre with multipurpose halls, landscaped courtyards and accessible facilities.', deadline: '2027-02-28', createdAt: date },
      { id: 'p5', companyId: 'c1', title: 'Jaipur Highway Expansion', city: 'Jaipur', category: 'Public infrastructure', budget: 48000000, duration: 300, area: '6 km corridor', status: 'Open', progress: 0, description: 'Road widening, drainage, retaining walls and service-road construction along an urban highway corridor.', deadline: '2027-04-30', createdAt: date },
      { id: 'p6', companyId: 'c2', title: 'Bangalore Metro Infrastructure', city: 'Bangalore', category: 'Public infrastructure', budget: 72000000, duration: 360, area: '2 station approach zones', status: 'Open', progress: 0, description: 'Civil works for station approaches, utility ducts, pedestrian access and precast support structures.', deadline: '2027-05-15', createdAt: date },
      { id: 'p7', companyId: 'c1', title: 'Hyderabad School Building', city: 'Hyderabad', category: 'Public infrastructure', budget: 9600000, duration: 210, area: '28,000 sq ft', status: 'Open', progress: 0, description: 'A three-storey school building with classrooms, laboratories, accessible ramps and a playground boundary.', deadline: '2027-04-20', createdAt: date },
      { id: 'p8', companyId: 'c2', title: 'Mumbai Industrial Facility', city: 'Mumbai', category: 'Industrial', budget: 24500000, duration: 240, area: '85,000 sq ft', status: 'Open', progress: 0, description: 'Factory foundations, machine bases, reinforced flooring and a steel-frame production shed.', deadline: '2027-05-10', createdAt: date }
    ],
    bids: [{ id: 'b1', projectId: 'p4', contractorId: 't1', amount: 2980000, days: 90, proposal: 'Dedicated 12-person team with weekly progress reporting and milestone delivery.', status: 'Accepted', date }],
    assignments: [{ id: 'a1', projectId: 'p4', contractorId: 't1', workerId: 'w1', rate: 900 }, { id: 'a2', projectId: 'p4', contractorId: 't1', workerId: 'w2', rate: 1100 }],
    attendance: [{ id: 'h1', projectId: 'p4', contractorId: 't1', workerId: 'w1', date, status: 'Present', rate: 900 }, { id: 'h2', projectId: 'p4', contractorId: 't1', workerId: 'w2', date, status: 'Present', rate: 1100 }],
    payments: [{ id: 'pay1', fromId: 'c1', toId: 't1', projectId: 'p4', amount: 250000, date, note: 'Mobilisation advance', method: 'Bank transfer', status: 'Paid' }, { id: 'pay2', fromId: 't1', toId: 'w1', projectId: 'p4', amount: 450, date, note: 'Part-day wage settlement', method: 'UPI', status: 'Paid' }],
    expenses: [{ id: 'x1', contractorId: 't1', projectId: 'p4', category: 'Materials', amount: 72000, date, note: 'Cement and TMT delivery' }, { id: 'x2', contractorId: 't1', projectId: 'p4', category: 'Transport', amount: 8500, date, note: 'Site material transport' }],
    equipment: [
      { id: 'e1', ownerId: 'c1', name: 'JCB 3DX Backhoe Loader', category: 'Earthmoving', city: 'Delhi', rate: 6500, available: true, specs: '74 HP · 4.77 m digging depth · Operator included', description: 'Versatile backhoe for excavation, trenching and material handling. Serviced between rentals.' },
      { id: 'e2', ownerId: 'c2', name: 'Tata Signa 2823 Tipper', category: 'Transport', city: 'Pune', rate: 4800, available: true, specs: '28 tonne GVW · 16 m³ body · Driver included', description: 'Reliable heavy-duty tipper for aggregates, sand and site clearance.' },
      { id: 'e3', ownerId: 'c1', name: 'ACE Hydra 14T Crane', category: 'Lifting', city: 'Noida', rate: 8200, available: true, specs: '14 tonne capacity · 15 m boom · Operator included', description: 'Pick-and-carry crane for structural erection and unloading.' },
      { id: 'e4', ownerId: 'c2', name: 'Schwing Concrete Mixer', category: 'Concrete', city: 'Mumbai', rate: 3500, available: true, specs: '6 m³ capacity · Transit mixer · Daily rental', description: 'Consistent concrete delivery for slab pours and foundation work.' },
      { id: 'e5', ownerId: 'c1', name: 'Tata Hitachi Excavator', category: 'Earthmoving', city: 'Jaipur', rate: 10500, available: true, rating: 4.7, specs: '20 tonne · 0.9 m³ bucket · Operator included', description: 'Tracked excavator for bulk earthwork, foundations and trench excavation.' },
      { id: 'e6', ownerId: 'c2', name: 'BEML Bulldozer', category: 'Earthmoving', city: 'Bangalore', rate: 14500, available: true, rating: 4.9, specs: '180 HP · Crawler tracks · Site grading', description: 'Heavy-duty bulldozer for clearing, levelling and large infrastructure earthworks.' },
      { id: 'e7', ownerId: 'c1', name: 'Kirloskar Generator', category: 'Power', city: 'Hyderabad', rate: 2800, available: true, rating: 4.6, specs: '62.5 kVA · Silent canopy · Diesel', description: 'Temporary site power for lighting, tools and construction offices. Fuel is not included.' }
    ], rentals: [],
    notifications: [{ id: 'n1', userId: 'c1', title: 'Your workspace is ready', message: 'Publish a project or review your active site.', read: false, date, path: '/company/projects' }, { id: 'n2', userId: 't1', title: 'Greenfield is active', message: 'Manage your team, attendance and site expenses.', read: false, date, path: '/contractor/active-projects' }, { id: 'n3', userId: 'w1', title: 'Payment received', message: '₹450 has been recorded for Greenfield Community Centre.', read: false, date, path: '/worker/payment-history' }],
    reviews: [{ id: 'r1', workerId: 'w1', author: 'Vikram Construction Co.', rating: 5, date, text: 'Reliable workmanship and excellent attention to brick alignment.' }, { id: 'r2', workerId: 'w2', author: 'Vikram Construction Co.', rating: 5, date, text: 'Careful installation and a tidy site handover.' }], settings: {}
  };
}
